language: node_js

sudo: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  ssh_known_hosts:
    - stephenlam.me

before_script:
  - openssl aes-256-cbc -K $encrypted_11309f95a964_key -iv $encrypted_11309f95a964_v -in ./public/webfonts/webfonts.zip.enc -out ./public/webfonts/webfonts.zip -d
  - npm run webfonts

script:
  - npm test
  - npm run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_c190e59dec8d_key -iv $encrypted_c190e59dec8d_iv -in deploy_key.enc -out /tmp/${TRAVIS_BUILD_ID}_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/${TRAVIS_BUILD_ID}_key
  - ssh-add /tmp/${TRAVIS_BUILD_ID}_key

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    all_branches: true
